[default]
TEST_ONLY = false

IS_TESTING_LR_RANGE = false
BERT_MLM_CHECKPOINT_PATH = "pretrained/BERT_pretrained_mlm.pth"          # "projects/finetune_bert/output/20210520_220426_807989/24trained_model.pth"
BERT_BOTTLE_CHECKPOINT_PATH = "pretrained/BERT_pretrained_on_bottle.pth" # "projects/bert-bottle-classification/output/20210619_134758_541359/7trained_model.pth"
VIT_IMAGENET_CHECKPOINT_PATH = "pretrained/ViT-B_16.npz"
OUTPUT_DIR = "./outputs"
USE_AMP = true
SEED = 42

LR = 3e-5
LR_COSINE_T0 = 500
LR_COSINE_T_MULT = 1
num_T = 25
use_num_T = true
use_multistep = false
lr_no_restarts = false
LR_WARMUP_STEP = 500
NUM_EPOCHS = 50
BATCH_SIZE_PERGPU = 8
NUM_WORKERS = 8
SGD_WEIGHT_DECAY = 0
SGD_MOMENTUM = 0.9
accum_iters = 32

SAVE_MODEL_EVERY_STEP = 8000
VALIDATION_EVERY_STEP = 200
LOG_EVERY_STEP = 50

# CPU_NUM_THREADS = 8
DEVICE = "cuda"
