# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 */12 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 30
        stale-issue-message: 'This issue is inactive for a while. Marked as staled.'
        stale-pr-message: 'This pull request is inactive for a while. Marked as staled.'
        stale-issue-label: 'staled'
        stale-pr-label: 'staled'
        days-before-close: 0
#         close-issue-message: 'Stale issue.'
#         close-pr-message: 'Stale pull request.'
